# Setup
title:        NODE XYZ
tagline:      Microservice microframework for node
baseurl:      ""
# paginate:     1

# About/contact
author:
  name:       Kian Peymani
  github:   kianengima
  twitter:  kianengima

# Gems
gems:
  - jekyll-paginate

include: ['_pages', 'apidoc', 'apidoc/modules', 'apidoc/interfaces', 'apidoc/classes']
exclude: ['example/*']
keep_files: ['./apidoc/*', './apidoc/modules', './apidoc/interfaces', './apidoc/classes']
#Others
markdown: kramdown

kramdown:
  syntax_highlighter: rouge
